// mkvtool v2 build. See PORTING-GUIDELINES.md ("Conventions established during the
// port") and PORTING-TODO.md task 0.1. Versions come from gradle.properties.

plugins {
    // Versions supplied by pluginManagement in settings.gradle.kts.
    kotlin("jvm")
    // kapt runs picocli-codegen: it is a javac annotation processor, so KSP cannot
    // run it. picocli-codegen generates the GraalVM reflection config under
    // META-INF/native-image, consumed by the native-image build in task 0.3.
    kotlin("kapt")
    // installDist provides the dev launcher; also names it via applicationName below.
    application
    // Maintained shadow fork (com.gradleup.*); the old johnrengelman fork is dead.
    // Wires shadowJar into `assemble`, so `build` produces the fat jar.
    id("com.gradleup.shadow")
}

group = "org.plukh"
// version is inherited from gradle.properties.

val picocliVersion = providers.gradleProperty("picocliVersion").get()
val kotestVersion = providers.gradleProperty("kotestVersion").get()

// JDK 21 (LTS) toolchain via Gradle toolchains — compilation and test execution use
// JDK 21 regardless of the JDK that launched Gradle.
kotlin {
    jvmToolchain(21)
}

application {
    mainClass.set("org.plukh.mkvtool.cli.MainKt")
    // Makes the installDist / distribution launcher be named `mkvtool` (+ .bat).
    applicationName = "mkvtool"
}

dependencies {
    implementation("info.picocli:picocli:$picocliVersion")
    kapt("info.picocli:picocli-codegen:$picocliVersion")

    testImplementation("io.kotest:kotest-runner-junit5:$kotestVersion")
    testImplementation("io.kotest:kotest-assertions-core:$kotestVersion")
}

// Version is defined once (project.version, from gradle.properties) and surfaced to
// the runtime through a generated Kotlin source. A compiled-in `const` needs no
// classpath resource loading, so it behaves identically under installDist, the shadow
// jar, and native-image with zero resource-inclusion config — unlike a bundled
// .properties resource, which native-image would need told about explicitly.
val generateBuildInfo = tasks.register("generateBuildInfo") {
    val version = project.version.toString()
    val outputDir = layout.buildDirectory.dir("generated/buildinfo")
    inputs.property("version", version)
    outputs.dir(outputDir)
    doLast {
        val pkgDir = outputDir.get().asFile.resolve("org/plukh/mkvtool")
        pkgDir.mkdirs()
        pkgDir.resolve("BuildInfo.kt").writeText(
            """
            package org.plukh.mkvtool

            /** Build-time facts, generated by the `generateBuildInfo` Gradle task. */
            internal object BuildInfo {
                const val VERSION: String = "$version"
            }
            """.trimIndent() + "\n",
            Charsets.UTF_8,
        )
    }
}

// Passing the task provider to srcDir wires both the generated directory and the
// compileKotlin -> generateBuildInfo dependency.
kotlin.sourceSets.main {
    kotlin.srcDir(generateBuildInfo)
}

tasks.test {
    useJUnitPlatform()
}

tasks.jar {
    manifest {
        attributes("Implementation-Version" to project.version)
    }
}

tasks.shadowJar {
    // Make the fat jar runnable via `java -jar`.
    manifest {
        attributes("Main-Class" to application.mainClass.get())
    }
}
